export { default as AppMain } from './app-main.vue'
export { default as Navbar } from './nav-bar/index.vue'
export { default as Settings } from './settings-view/index.vue'
export { default as SlideMenu } from './slide-menu/index.vue'
export { default as TagsView } from './tags-view/index.vue'
